### ISSUE TITLE
Self analysis

### ISSUE THREAD

**Issue by h2grover** [anjaliahlawat/amazon-login-script#55]
Good job on progressing till here. I need you to take a step back and do a self analysis. 

Questions you should ask to yourself
1. What I learned during this ramp-up session
1. How it is helping me in future growth
1. What things I missed and could have been better.
1. Things you learned related to Qa if any.
1. How can I improve/refine this framework more.

Please answer any many questions as you can in this issue itself.

**Comment by h2grover** [comment]
@anjaliahlawat can you please post your thoughts on priority

**Comment by anjaliahlawat** [comment]
**What I learnt -** 

Technically - 
1. Git and its basic concepts and how to work in collaboration on github 
2. Git hooks and their use 
3. Eslint 
4. Commitlint 
5. Typescript 
6. POM pattern 
7. Automation testing 
8. STLC 

General - 
1. Importance of testing 
2. Keep refactoring and improvising the code. 
3. Don't add anything in code unless you know what it truly does. 
4. Pay attention to details  

**How it is helping me in future growth -** 

1. It will help me to write good quality code. 
2. It taught me how to develop clean and reusable code. 
3. It taught me how to approach a problem.  

**What things I missed and could have been better.** 
1. Knowledge of git and how to properly to use it. 
2. Code refactoring  
3. Going through documentation.  
4. Proper naming of functions and variables as they are important. 
5. Make each function responsible for handling single task only. 

**Things I learned related to Qa if any -** 

I still didn't have exposure to QA since I have only created one login script. But I understand the automation testing and how much accuracy is needed as each and every step needs to be check and handled properly. 

 
**How can I improve/refine this framework more-** 

1. I think our errors can be handled or logged on console in a better way. It's messy and difficult to understand problems from console. We can log our errors in some other tools available online. 

I think the code is much cleaner and better now although there's always a scope for improvement.

**Comment by h2grover** [comment]
Ok thanks for posting your thoughts. Please close this ticket now
